name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: windows-2022
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 200.234.232.44
          port: 2222
          username: miriam
          key: ${{ secrets.PRIVATE_KEY }}
          script: "cd C:\\laragon\\www\\pruebaDPL; git pull origin main; npm run build"
